import type { CollectionDefinition, GlobalDefinition, ComponentDefinition } from "@blaze-cms/types";

import { writeFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";

import type { Generator } from "./generator.js";

export class TypeGenerator implements Generator {
  name = "types";

  async generate(
    collections: CollectionDefinition[],
    globals: GlobalDefinition[],
    _components: ComponentDefinition[],
    outDir: string,
  ): Promise<void> {
    mkdirSync(outDir, { recursive: true });
    let output = "// Auto-generated by Blaze CMS — do not edit\n\n";

    for (const collection of collections) {
      const name = pascalCase(collection.slug);
      output += `export interface ${name} {\n`;
      output += `  id: string;\n`;
      output += `  createdAt: string;\n`;
      output += `  updatedAt: string;\n`;
      for (const field of collection.fields) {
        output += `  ${field.name}: ${fieldTypeToTS(field.type)};\n`;
      }
      output += `}\n\n`;
    }

    for (const global of globals) {
      const name = pascalCase(global.slug);
      output += `export interface ${name} {\n`;
      for (const field of global.fields) {
        output += `  ${field.name}: ${fieldTypeToTS(field.type)};\n`;
      }
      output += `}\n\n`;
    }

    writeFileSync(resolve(outDir, "types.ts"), output);
  }
}

function pascalCase(str: string): string {
  return str
    .replace(/[-_](.)/g, (_: string, c: string) => c.toUpperCase())
    .replace(/^(.)/, (_: string, c: string) => c.toUpperCase());
}

function fieldTypeToTS(type: string): string {
  const map: Record<string, string> = {
    boolean: "boolean",
    checkbox: "boolean",
    code: "string",
    color: "string",
    date: "string",
    datetime: "string",
    email: "string",
    json: "unknown",
    markdown: "string",
    media: "string",
    multiSelect: "string[]",
    number: "number",
    password: "string",
    radio: "string",
    relation: "string",
    richText: "string",
    select: "string",
    slug: "string",
    text: "string",
    textarea: "string",
    upload: "string",
    url: "string",
  };
  return map[type] ?? "string";
}
