// Auto-generated by Blazing CMS — do not edit
export const projectName = "Blazing CMS Playground";
export const capabilities: import("@blazing-cms/types").ResolvedCapabilities = {
  features: {
    content: true,
    analytics: false,
    media: true,
    versioning: true,
    workflow: true,
    notifications: true,
    rbac: true,
  },
  collections: {
    date: {
      versioning: false,
    },
  },
  globals: {},
};
