// Auto-generated by Blaze CMS — do not edit manually
// Run `blaze generate` to regenerate from your cms/ schemas

import type { CollectionDefinition, GlobalDefinition, ComponentDefinition } from "@blaze-cms/types";

export const collections: CollectionDefinition[] = [];
export const globals: GlobalDefinition[] = [];
export const components: ComponentDefinition[] = [];

export function getCollection(slug: string): CollectionDefinition | undefined {
  return collections.find((c) => c.slug === slug);
}
export function getGlobal(slug: string): GlobalDefinition | undefined {
  return globals.find((g) => g.slug === slug);
}
export function getComponent(slug: string): ComponentDefinition | undefined {
  return components.find((c) => c.slug === slug);
}
