import {
  TypeGenerator,
  ValidationGenerator,
  SdkGenerator,
  GenerationPipeline,
} from "@blaze-cms/generators";
import { SchemaLoader } from "@blaze-cms/schema";
import { resolve } from "node:path";
import { writeFileSync, mkdirSync, existsSync } from "node:fs";

export interface GenerateOptions {
  type?: string;
  dir?: string;
}

async function generateSchemaRegistry(collections: unknown[], globals: unknown[], components: unknown[], outDir: string) {
  const content = `
// Auto-generated by Blaze CMS — do not edit
import type { CollectionDefinition, GlobalDefinition, ComponentDefinition } from "@blaze-cms/types";

export const collections: CollectionDefinition[] = ${JSON.stringify(collections, null, 2)};
export const globals: GlobalDefinition[] = ${JSON.stringify(globals, null, 2)};
export const components: ComponentDefinition[] = ${JSON.stringify(components, null, 2)};

export function getCollection(slug: string): CollectionDefinition | undefined {
  return collections.find((c) => c.slug === slug);
}
export function getGlobal(slug: string): GlobalDefinition | undefined {
  return globals.find((g) => g.slug === slug);
}
export function getComponent(slug: string): ComponentDefinition | undefined {
  return components.find((c) => c.slug === slug);
}
`;
  writeFileSync(resolve(outDir, "schema-registry.ts"), content.trimStart());
  console.warn(`  ✓ Generated schema-registry.ts`);
}

async function generateFirestoreRules(collections: unknown[]) {
  const rules = `
rules_version = 2;
service cloud.firestore {
  match /databases/{database}/documents {
    // Admin access — Firebase Auth required
    match /{document=**} {
      allow read, write: if request.auth != null;
    }
  }
}
`;
  writeFileSync(resolve(process.cwd(), "firestore.rules"), rules.trimStart());
  console.warn(`  ✓ Generated firestore.rules`);
}

async function generateFirestoreIndexes(collections: unknown[]) {
  const indexes = {
    indexes: [] as unknown[],
  };
  writeFileSync(resolve(process.cwd(), "firestore.indexes.json"), JSON.stringify(indexes, null, 2));
  console.warn(`  ✓ Generated firestore.indexes.json`);
}

export async function generate(options: GenerateOptions): Promise<void> {
  const schemaDir = resolve(process.cwd(), options.dir ?? "cms");
  const outDir = resolve(process.cwd(), "src/admin/__generated__");

  if (!existsSync(schemaDir)) {
    console.warn(`  ⚠ Schema directory not found: ${schemaDir}`);
    console.warn("  Skipping code generation.\n");
    return;
  }

  console.warn(`  Loading schemas from ${schemaDir}...`);
  const loader = new SchemaLoader(schemaDir);
  const schema = await loader.load();

  console.warn(`  Found ${schema.collections.length} collections, ${schema.globals.length} globals\n`);

  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }

  const pipeline = new GenerationPipeline();

  if (!options.type || options.type === "types") {
    pipeline.addGenerator(new TypeGenerator());
  }
  if (!options.type || options.type === "validation") {
    pipeline.addGenerator(new ValidationGenerator());
  }
  if (!options.type || options.type === "sdk") {
    pipeline.addGenerator(new SdkGenerator());
  }
  if (!options.type || options.type === "registry") {
    await generateSchemaRegistry(schema.collections, schema.globals, schema.components, outDir);
  }
  if (!options.type || options.type === "rules") {
    await generateFirestoreRules(schema.collections);
  }
  if (!options.type || options.type === "indexes") {
    await generateFirestoreIndexes(schema.collections);
  }

  await pipeline.run(schema.collections, schema.globals, schema.components, outDir);

  if (!options.type) {
    console.warn(`\n  Generated files in ${outDir}`);
  }
}
