import {
  TypeGenerator,
  ValidationGenerator,
  SdkGenerator,
  GenerationPipeline,
} from "@blaze-cms/generators";
import { SchemaLoader } from "@blaze-cms/schema";
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
export interface GenerateOptions {
  type?: string;
  dir?: string;
  outDir?: string;
  sync?: boolean;
}

async function generateSchemaRegistry(collections: unknown[], globals: unknown[], components: unknown[], outDir: string) {
  const content = `
// Auto-generated by Blaze CMS — do not edit
import type { CollectionDefinition, GlobalDefinition, ComponentDefinition } from "@blaze-cms/types";

export const collections: CollectionDefinition[] = ${JSON.stringify(collections, null, 2)};
export const globals: GlobalDefinition[] = ${JSON.stringify(globals, null, 2)};
export const components: ComponentDefinition[] = ${JSON.stringify(components, null, 2)};

export function getCollection(slug: string): CollectionDefinition | undefined {
  return collections.find((c) => c.slug === slug);
}
export function getGlobal(slug: string): GlobalDefinition | undefined {
  return globals.find((g) => g.slug === slug);
}
export function getComponent(slug: string): ComponentDefinition | undefined {
  return components.find((c) => c.slug === slug);
}
`;
  writeFileSync(resolve(outDir, "schema-registry.ts"), content.trimStart());
  console.warn(`  ✓ Generated schema-registry.ts`);
}

async function generateFirestoreRules(collections: { slug: string }[], globals: { slug: string }[]) {
  const collectionRules = collections
    .map((c) => `    match /${c.slug}/{doc} {\n      allow read, write: if request.auth != null;\n    }`)
    .join("\n");
  const globalRules = globals
    .map((g) => `    match /globals_${g.slug}/{doc} {\n      allow read, write: if request.auth != null;\n    }`)
    .join("\n");

  const rules = `
rules_version = 2;
service cloud.firestore {
  match /databases/{database}/documents {

    // Schemas — readable by all authenticated users, writable only by admins
    match /_schemas/{collection}/{doc} {
      allow read: if request.auth != null;
      allow write: if request.auth != null && request.auth.token.admin == true;
    }

    // Per-collection content rules
${collectionRules}

    // Global content rules
${globalRules}

    // Deny everything else
    match /{document=**} {
      allow read, write: if false;
    }
  }
}
`;
  writeFileSync(resolve(process.cwd(), "firestore.rules"), rules.trimStart());
  console.warn(`  ✓ Generated firestore.rules`);
}

async function generateFirestoreIndexes(collections: unknown[]) {
  const indexes = {
    indexes: [] as unknown[],
  };
  writeFileSync(resolve(process.cwd(), "firestore.indexes.json"), JSON.stringify(indexes, null, 2));
  console.warn(`  ✓ Generated firestore.indexes.json`);
}

const _dirname = fileURLToPath(new URL(".", import.meta.url));
const ADMIN_ROOT = resolve(_dirname, "../../src/admin");

export async function generate(options: GenerateOptions): Promise<void> {
  const schemaDir = resolve(process.cwd(), options.dir ?? "cms");
  const outDir = options.outDir ? resolve(process.cwd(), options.outDir) : resolve(ADMIN_ROOT, "__generated__");

  if (!existsSync(schemaDir)) {
    console.warn(`  ⚠ Schema directory not found: ${schemaDir}`);
    console.warn("  Skipping code generation.\n");
    return;
  }

  console.warn(`  Loading schemas from ${schemaDir}...`);
  const loader = new SchemaLoader(schemaDir);
  const schema = await loader.load();

  console.warn(`  Found ${schema.collections.length} collections, ${schema.globals.length} globals\n`);

  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }

  const pipeline = new GenerationPipeline();

  if (!options.type || options.type === "types") {
    pipeline.addGenerator(new TypeGenerator());
  }
  if (!options.type || options.type === "validation") {
    pipeline.addGenerator(new ValidationGenerator());
  }
  if (!options.type || options.type === "sdk") {
    pipeline.addGenerator(new SdkGenerator());
  }
  if (!options.type || options.type === "registry") {
    await generateSchemaRegistry(schema.collections, schema.globals, schema.components, outDir);
  }
  if (!options.type || options.type === "rules") {
    await generateFirestoreRules(schema.collections, schema.globals);
  }
  if (!options.type || options.type === "indexes") {
    await generateFirestoreIndexes(schema.collections);
  }

  await pipeline.run(schema.collections, schema.globals, schema.components, outDir);

  if (!options.type) {
    console.warn(`\n  Generated files in ${outDir}`);
  }

  if (options.sync) {
    const { syncToFirestore } = await import("./sync-to-firestore.js");
    await syncToFirestore({
      collections: schema.collections as never,
      globals: schema.globals as never,
      components: schema.components as never,
    });
  }
}
