// Auto-generated by Blaze CMS — do not edit
import type { CollectionDefinition, GlobalDefinition, ComponentDefinition } from "@blaze-cms/types";

export const collections: CollectionDefinition[] = [
  {
    "fields": [
      {
        "label": "Title",
        "name": "title",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "fields": [
          {
            "label": "Item",
            "name": "item",
            "type": "text"
          }
        ],
        "label": "Array Field",
        "name": "field",
        "type": "array"
      }
    ],
    "labels": {
      "plural": "Array Fields",
      "singular": "Array Field"
    },
    "slug": "array"
  },
  {
    "fields": [
      {
        "label": "Title",
        "name": "title",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "label": "Boolean Field",
        "name": "field",
        "type": "boolean"
      }
    ],
    "labels": {
      "plural": "Boolean Fields",
      "singular": "Boolean Field"
    },
    "slug": "boolean"
  },
  {
    "fields": [
      {
        "label": "Title",
        "name": "title",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "component": "seo",
        "label": "Component Field",
        "name": "field",
        "type": "component"
      }
    ],
    "labels": {
      "plural": "Component Fields",
      "singular": "Component Field"
    },
    "slug": "component"
  },
  {
    "fields": [
      {
        "label": "Title",
        "name": "title",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "label": "Date Field",
        "name": "field",
        "type": "date"
      }
    ],
    "labels": {
      "plural": "Date Fields",
      "singular": "Date Field"
    },
    "slug": "date"
  },
  {
    "fields": [
      {
        "label": "Title",
        "name": "title",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "components": [
          "seo",
          "media-card"
        ],
        "label": "Dynamic Zone Field",
        "name": "field",
        "type": "dynamicZone"
      }
    ],
    "labels": {
      "plural": "Dynamic Zone Fields",
      "singular": "Dynamic Zone Field"
    },
    "slug": "dynamic-zone"
  },
  {
    "fields": [
      {
        "label": "Title",
        "name": "title",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "fields": [
          {
            "label": "Nested",
            "name": "nested",
            "type": "text"
          }
        ],
        "label": "Group Field",
        "name": "field",
        "type": "group"
      }
    ],
    "labels": {
      "plural": "Group Fields",
      "singular": "Group Field"
    },
    "slug": "group"
  },
  {
    "fields": [
      {
        "label": "Title",
        "name": "title",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "label": "Media Field",
        "name": "field",
        "type": "media"
      }
    ],
    "labels": {
      "plural": "Media Fields",
      "singular": "Media Field"
    },
    "slug": "media-test"
  },
  {
    "fields": [
      {
        "label": "Title",
        "name": "title",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "label": "Number Field",
        "name": "field",
        "type": "number"
      }
    ],
    "labels": {
      "plural": "Number Fields",
      "singular": "Number Field"
    },
    "slug": "number"
  },
  {
    "admin": {
      "defaultSort": "-createdAt",
      "useAsTitle": "title"
    },
    "fields": [
      {
        "label": "Title",
        "name": "title",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "name": "slug",
        "source": "title",
        "type": "slug",
        "unique": true
      },
      {
        "label": "Excerpt",
        "name": "excerpt",
        "type": "textarea"
      },
      {
        "label": "Content",
        "name": "content",
        "type": "text"
      },
      {
        "defaultValue": false,
        "label": "Published",
        "name": "published",
        "type": "boolean"
      },
      {
        "label": "Published At",
        "name": "publishedAt",
        "type": "datetime"
      },
      {
        "label": "Category",
        "name": "category",
        "options": [
          {
            "label": "News",
            "value": "news"
          },
          {
            "label": "Tutorial",
            "value": "tutorial"
          },
          {
            "label": "Blog",
            "value": "blog"
          }
        ],
        "type": "select"
      },
      {
        "kind": "manyToOne",
        "label": "Author",
        "name": "author",
        "to": "users",
        "type": "relation"
      }
    ],
    "labels": {
      "plural": "Posts",
      "singular": "Post"
    },
    "slug": "posts",
    "timestamps": {
      "createdAt": true,
      "updatedAt": true
    }
  },
  {
    "fields": [
      {
        "label": "Title",
        "name": "title",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "label": "Relation Field",
        "name": "field",
        "to": "users",
        "type": "relation"
      }
    ],
    "labels": {
      "plural": "Relation Fields",
      "singular": "Relation Field"
    },
    "slug": "relation"
  },
  {
    "fields": [
      {
        "label": "Title",
        "name": "title",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "fields": [
          {
            "label": "Item",
            "name": "item",
            "type": "text"
          }
        ],
        "label": "Repeater Field",
        "name": "field",
        "type": "repeater"
      }
    ],
    "labels": {
      "plural": "Repeater Fields",
      "singular": "Repeater Field"
    },
    "slug": "repeater"
  },
  {
    "fields": [
      {
        "label": "Title",
        "name": "title",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "label": "Rich Text Field",
        "name": "field",
        "type": "richText"
      }
    ],
    "labels": {
      "plural": "Rich Text Fields",
      "singular": "Rich Text Field"
    },
    "slug": "rich-text"
  },
  {
    "fields": [
      {
        "label": "Title",
        "name": "title",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "label": "Select Field",
        "name": "field",
        "options": [
          {
            "label": "Option A",
            "value": "option-a"
          },
          {
            "label": "Option B",
            "value": "option-b"
          },
          {
            "label": "Option C",
            "value": "option-c"
          }
        ],
        "type": "select"
      }
    ],
    "labels": {
      "plural": "Select Fields",
      "singular": "Select Field"
    },
    "slug": "select"
  },
  {
    "fields": [
      {
        "label": "Title",
        "name": "title",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "label": "Text Field",
        "name": "field",
        "type": "text"
      }
    ],
    "labels": {
      "plural": "Text Fields",
      "singular": "Text Field"
    },
    "slug": "text"
  }
];
export const globals: GlobalDefinition[] = [
  {
    "admin": {
      "group": "Content"
    },
    "fields": [
      {
        "label": "Hero Title",
        "name": "heroTitle",
        "type": "text"
      },
      {
        "label": "Hero Subtitle",
        "name": "heroSubtitle",
        "type": "text"
      },
      {
        "defaultValue": true,
        "label": "Show Featured Posts",
        "name": "showFeaturedPosts",
        "type": "boolean"
      },
      {
        "kind": "oneToOne",
        "label": "Featured Post",
        "name": "featuredPost",
        "to": "posts",
        "type": "relation"
      }
    ],
    "label": "Homepage",
    "slug": "homepage"
  },
  {
    "admin": {
      "group": "Settings"
    },
    "fields": [
      {
        "label": "Site Name",
        "name": "siteName",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "label": "Tagline",
        "name": "tagline",
        "type": "text"
      },
      {
        "label": "Description",
        "name": "description",
        "type": "textarea"
      },
      {
        "label": "Logo",
        "name": "logo",
        "type": "media"
      },
      {
        "format": "hex",
        "label": "Primary Color",
        "name": "primaryColor",
        "type": "color"
      },
      {
        "format": "hex",
        "label": "Secondary Color",
        "name": "secondaryColor",
        "type": "color"
      },
      {
        "defaultValue": true,
        "label": "Enable Comments",
        "name": "enableComments",
        "type": "boolean"
      }
    ],
    "label": "Site Settings",
    "slug": "site-settings"
  }
];
export const components: ComponentDefinition[] = [
  {
    "fields": [
      {
        "label": "Button Label",
        "name": "label",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "label": "URL",
        "name": "url",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "label": "Variant",
        "name": "variant",
        "options": [
          {
            "label": "Primary",
            "value": "primary"
          },
          {
            "label": "Secondary",
            "value": "secondary"
          },
          {
            "label": "Ghost",
            "value": "ghost"
          }
        ],
        "type": "select"
      },
      {
        "label": "Open in New Tab",
        "name": "openInNewTab",
        "type": "boolean"
      }
    ],
    "label": "Button",
    "slug": "button"
  },
  {
    "fields": [
      {
        "label": "Heading",
        "name": "heading",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "label": "Body",
        "name": "body",
        "type": "text"
      },
      {
        "label": "CTA Label",
        "name": "ctaLabel",
        "type": "text"
      },
      {
        "label": "CTA URL",
        "name": "ctaUrl",
        "type": "text"
      }
    ],
    "label": "CTA",
    "slug": "cta"
  },
  {
    "fields": [
      {
        "label": "Heading",
        "name": "heading",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "label": "Subheading",
        "name": "subheading",
        "type": "text"
      },
      {
        "label": "Background Image URL",
        "name": "backgroundImage",
        "type": "text"
      }
    ],
    "label": "Hero",
    "slug": "hero"
  },
  {
    "fields": [
      {
        "label": "Image",
        "name": "image",
        "type": "media",
        "validation": {
          "required": true
        }
      },
      {
        "label": "Title",
        "name": "title",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "label": "Description",
        "name": "description",
        "type": "textarea"
      },
      {
        "label": "Layout",
        "name": "layout",
        "options": [
          {
            "label": "Left",
            "value": "left"
          },
          {
            "label": "Right",
            "value": "right"
          },
          {
            "label": "Full",
            "value": "full"
          }
        ],
        "type": "select"
      }
    ],
    "label": "Media Card",
    "slug": "media-card"
  },
  {
    "fields": [
      {
        "label": "SEO Title",
        "name": "title",
        "type": "text",
        "validation": {
          "required": true
        }
      },
      {
        "label": "Meta Description",
        "name": "description",
        "type": "textarea"
      },
      {
        "label": "OG Image URL",
        "name": "ogImage",
        "type": "text"
      },
      {
        "label": "Canonical URL",
        "name": "canonicalUrl",
        "type": "text"
      }
    ],
    "label": "SEO",
    "slug": "seo"
  }
];

export function getCollection(slug: string): CollectionDefinition | undefined {
  return collections.find((c) => c.slug === slug);
}
export function getGlobal(slug: string): GlobalDefinition | undefined {
  return globals.find((g) => g.slug === slug);
}
export function getComponent(slug: string): ComponentDefinition | undefined {
  return components.find((c) => c.slug === slug);
}