// Auto-generated by Blaze CMS — do not edit

export interface Array {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface Boolean {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: boolean;
}

export interface Component {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface Date {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface DynamicZone {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface Group {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface MediaTest {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface Number {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: number;
}

export interface Posts {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  published: boolean;
  publishedAt: string;
  category: string;
  author: string;
}

export interface Relation {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface Repeater {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface RichText {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface Select {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface Text {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface Homepage {
  heroTitle: string;
  heroSubtitle: string;
  showFeaturedPosts: boolean;
  featuredPost: string;
}

export interface SiteSettings {
  siteName: string;
  tagline: string;
  description: string;
  logo: string;
  primaryColor: string;
  secondaryColor: string;
  enableComments: boolean;
}

